#ifndef MODAPI_EXAMPLE_DEF_H
#define MODAPI_EXAMPLE_DEF_H

enum
{
	MODAPIEXAMPLE_IMAGE_OBJECTS = 0,
};

enum
{
	MODAPIEXAMPLE_SPRITE_TARGET = 0,
	MODAPIEXAMPLE_SPRITE_LASERBEAM_START,
	MODAPIEXAMPLE_SPRITE_LASERBEAM_START2,
	MODAPIEXAMPLE_SPRITE_LASERBEAM_END,
	MODAPIEXAMPLE_SPRITE_LASERBEAM_END2,
};

enum
{
	MODAPIEXAMPLE_LINESTYLE_LASERBEAM = 0,
};

#endif
